using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Deluxe.QCReport.Common.Models
{
    public class AudioTC
    {
        public int qcNum { get; set; }
        public int subQCNum { get; set; }
        public string Language { get; set; }
        public string Ch1_Desc { get; set; }
        public string Ch1_Tone { get; set; }
        public string Ch1_Avg { get; set; }
        public string Ch1_Peak { get; set; }
        public string Ch1_TruePeak { get; set; }
        public string Ch2_Desc { get; set; }
        public string Ch2_Tone { get; set; }
        public string Ch2_Avg { get; set; }
        public string Ch2_Peak { get; set; }
        public string Ch2_TruePeak { get; set; }
        public string Ch3_Desc { get; set; }
        public string Ch3_Tone { get; set; }
        public string Ch3_Avg { get; set; }
        public string Ch3_Peak { get; set; }
        public string Ch3_TruePeak { get; set; }
        public string Ch4_Desc { get; set; }
        public string Ch4_Tone { get; set; }
        public string Ch4_Avg { get; set; }
        public string Ch4_Peak { get; set; }
        public string Ch4_TruePeak { get; set; }
        public string Ch5_Desc { get; set; }
        public string Ch5_Tone { get; set; }
        public string Ch5_Avg { get; set; }
        public string Ch5_Peak { get; set; }
        public string Ch5_TruePeak { get; set; }
        public string Ch6_Desc { get; set; }
        public string Ch6_Tone { get; set; }
        public string Ch6_Avg { get; set; }
        public string Ch6_Peak { get; set; }
        public string Ch6_TruePeak { get; set; }
        public string Ch7_Desc { get; set; }
        public string Ch7_Tone { get; set; }
        public string Ch7_Avg { get; set; }
        public string Ch7_Peak { get; set; }
        public string Ch7_TruePeak { get; set; }
        public string Ch8_Desc { get; set; }
        public string Ch8_Tone { get; set; }
        public string Ch8_Avg { get; set; }
        public string Ch8_Peak { get; set; }
        public string Ch8_TruePeak { get; set; }
        public string Cue_Desc { get; set; }
        public string Cue_Tone { get; set; }
        public string Cue_Avg { get; set; }
        public string Cue_Peak { get; set; }
        public string Cue_TruePeak { get; set; }
        public string Time_code { get; set; }
        public string NR { get; set; }
        public string TCInteg { get; set; }
        public string Comp_Sync { get; set; }
        public string ch12_phase { get; set; }
        public string Tone_Phase { get; set; }
        public string ch34_phase { get; set; }
        public string QCinUnity { get; set; }
        public string LTC_VITC_Match { get; set; }
        public string SurroundSound { get; set; }
        public string Ch9_Desc { get; set; }
        public string Ch9_Tone { get; set; }
        public string Ch9_Avg { get; set; }
        public string Ch9_Peak { get; set; }
        public string Ch9_TruePeak { get; set; }
        public string Ch10_Desc { get; set; }
        public string Ch10_Tone { get; set; }
        public string Ch10_Avg { get; set; }
        public string Ch10_Peak { get; set; }
        public string Ch10_TruePeak { get; set; }
        public string Ch11_Desc { get; set; }
        public string Ch11_Tone { get; set; }
        public string Ch11_Avg { get; set; }
        public string Ch11_Peak { get; set; }
        public string Ch11_TruePeak { get; set; }
        public string Ch12_Desc { get; set; }
        public string Ch12_Tone { get; set; }
        public string Ch12_Avg { get; set; }
        public string Ch12_Peak { get; set; }
        public string Ch12_TruePeak { get; set; }
        public string Ch13_Desc { get; set; }
        public string Ch13_Tone { get; set; }
        public string Ch13_Avg { get; set; }
        public string Ch13_Peak { get; set; }
        public string Ch13_TruePeak { get; set; }
        public string Ch14_Desc { get; set; }
        public string Ch14_Tone { get; set; }
        public string Ch14_Avg { get; set; }
        public string Ch14_Peak { get; set; }
        public string Ch14_TruePeak { get; set; }
        public string Ch15_Desc { get; set; }
        public string Ch15_Tone { get; set; }
        public string Ch15_Avg { get; set; }
        public string Ch15_Peak { get; set; }
        public string Ch15_TruePeak { get; set; }
        public string Ch16_Desc { get; set; }
        public string Ch16_Tone { get; set; }
        public string Ch16_Avg { get; set; }
        public string Ch16_Peak { get; set; }
        public string Ch16_TruePeak { get; set; }
        public string Ch1_LKFS { get; set; }
        public string Ch2_LKFS { get; set; }
        public string Ch3_LKFS { get; set; }
        public string Ch4_LKFS { get; set; }
        public string Ch5_LKFS { get; set; }
        public string Ch6_LKFS { get; set; }
        public string Ch7_LKFS { get; set; }
        public string Ch8_LKFS { get; set; }
        public string Ch9_LKFS { get; set; }
        public string Ch10_LKFS { get; set; }
        public string Ch11_LKFS { get; set; }
        public string Ch12_LKFS { get; set; }
        public string Ch13_LKFS { get; set; }
        public string Ch14_LKFS { get; set; }
        public string Ch15_LKFS { get; set; }
        public string Ch16_LKFS { get; set; }
        public string Cue_LKFS { get; set; }
        public string Ch17_Desc { get; set; }
        public string Ch17_Tone { get; set; }
        public string Ch17_Avg { get; set; }
        public string Ch17_Peak { get; set; }
        public string Ch17_TruePeak { get; set; }
        public string Ch17_LKFS { get; set; }
        public string Ch18_Desc { get; set; }
        public string Ch18_Tone { get; set; }
        public string Ch18_Avg { get; set; }
        public string Ch18_Peak { get; set; }
        public string Ch18_TruePeak { get; set; }
        public string Ch18_LKFS { get; set; }
        public string Ch19_Desc { get; set; }
        public string Ch19_Tone { get; set; }
        public string Ch19_Avg { get; set; }
        public string Ch19_Peak { get; set; }
        public string Ch19_TruePeak { get; set; }
        public string Ch19_LKFS { get; set; }
        public string Ch20_Desc { get; set; }
        public string Ch20_Tone { get; set; }
        public string Ch20_Avg { get; set; }
        public string Ch20_Peak { get; set; }
        public string Ch20_TruePeak { get; set; }
        public string Ch20_LKFS { get; set; }
        public string Ch21_Desc { get; set; }
        public string Ch21_Tone { get; set; }
        public string Ch21_Avg { get; set; }
        public string Ch21_Peak { get; set; }
        public string Ch21_TruePeak { get; set; }
        public string Ch21_LKFS { get; set; }
        public string Ch22_Desc { get; set; }
        public string Ch22_Tone { get; set; }
        public string Ch22_Avg { get; set; }
        public string Ch22_Peak { get; set; }
        public string Ch22_TruePeak { get; set; }
        public string Ch22_LKFS { get; set; }
        public string Ch23_Desc { get; set; }
        public string Ch23_Tone { get; set; }
        public string Ch23_Avg { get; set; }
        public string Ch23_Peak { get; set; }
        public string Ch23_TruePeak { get; set; }
        public string Ch23_LKFS { get; set; }
        public string Ch24_Desc { get; set; }
        public string Ch24_Tone { get; set; }
        public string Ch24_Avg { get; set; }
        public string Ch24_Peak { get; set; }
        public string Ch24_TruePeak { get; set; }
        public string Ch24_LKFS { get; set; }
        public string Language1 { get; set; }
        public string Language2 { get; set; }
        public string Language3 { get; set; }
        public string Language4 { get; set; }
        public string Language5 { get; set; }
        public string Language6 { get; set; }
        public string Language7 { get; set; }
        public string Language8 { get; set; }
        public string Language9 { get; set; }
        public string Language10 { get; set; }
        public string Language11 { get; set; }
        public string Language12 { get; set; }
        public string Language13 { get; set; }
        public string Language14 { get; set; }
        public string Language15 { get; set; }
        public string Language16 { get; set; }
        public string Language17 { get; set; }
        public string Language18 { get; set; }
        public string Language19 { get; set; }
        public string Language20 { get; set; }
        public string Language21 { get; set; }
        public string Language22 { get; set; }
        public string Language23 { get; set; }
        public string Language24 { get; set; }
        public string ChannelCount { get; set; }
    }
}
